gestionp/urls.py
import statistics
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gestionpfe.urls',namespace='gestionpfe')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('social-auth/', include('social_django.urls', namespace="social")),
    
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionpfe/urls.py
from django.urls import path
from . import views
from django.views.static import serve 

app_name="gestionpfe"
urlpatterns = [
    path('',views.home,name='home'),
    path('signup/',views.register_request,name='signup'),
    path('monome/',views.monome,name='monome'),
    path('binome/',views.binome,name='binome'),
    path('updatebinome/',views.updateDatabinome,name="updatebinome"),
    path('updatemonome/',views.updateDatamonome,name="updatemonome"),
    path('CahierCharge/',views.cahierC,name='demandeC'),
    path('ficherecap/',views.ficherecap,name='ficherecap'),
    path('test/',views.subscribe,name='subscribe'),
    path("reponse/<int:pk>/<slug:userlogin>/",views.reponse,name='reponse'),
    path("notif/",views.notifier,name='notifier'),
    
    
    
    
]

templates/includes/footer.html
{% load static %}
<footer class="footer">

  <!-- Footer Top -->
  <div class="footer-top">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-3 col-md-6">

          <!-- Footer Widget -->
          <div class="footer-widget footer-about">
            <div class="footer-logo">
              <img src="{% static 'img/logo11.png' %}" alt="logo" style="width:90px;height:90px">
            </div>
            <div class="footer-about-content">
              
              <div class="social-icon">
                <ul>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-facebook-f"></i> </a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-twitter"></i> </a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                  </li>
                  <li>
                    <a href="#" target="_blank"><i class="fab fa-dribbble"></i> </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <!-- /Footer Widget -->

        </div>

        <div class="col-lg-3 col-md-6">

          <!-- Footer Widget -->
          <div class="footer-widget footer-menu">
            <h2 class="footer-title">About</h2>
            <ul>
              <li><a href="search.html">Institut Supérieur des Etudes Technologiques de Nabeuls</a></li>
              <li> <p style="color:white">Envie d'améliorer votre candidature! Bienvenue sur la plateforme professionnelle de gestion des PFE de l'ISET</p></li>
            </ul>
          </div>
          <!-- /Footer Widget -->

        </div>

        <div class="col-lg-3 col-md-6">
        </div>

        <div class="col-lg-3 col-md-6">

          <!-- Footer Widget -->
          <div class="footer-widget footer-contact">
            <h2 class="footer-title">Contact Us</h2>
            <div class="footer-contact-info">
              <div class="footer-address">
                <span><i class="fas fa-map-marker-alt"></i></span>
                <p> Mrezgua Nabeul</p>
              </div>
              <p>
                <i class="fas fa-phone-alt"></i>
                +216 24 382 008
              </p>
              <p class="mb-0">
                <i class="fas fa-envelope"></i>
                isetnabeul@gmail.com
              </p>
            </div>
          </div>
          <!-- /Footer Widget -->
        </div>

      </div>
    </div>
  </div>
  <!-- /Footer Top -->

  <!-- Footer Bottom -->
         
  <!-- /Footer Bottom -->

</footer>

templates/includes/header.html
{% load static %}
<header class="header">
  <nav class="navbar navbar-expand-lg header-nav">
    <div class="navbar-header">
      <a id="mobile_btn" href="javascript:void(0);">
        <span class="bar-icon">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </a>
      <a href="index.html" class="navbar-brand logo">
        <img src="{% static 'img/logo11.png' %}" class="img-fluid" alt="Logo" style="width:50px;height:50px">
      </a>
    </div>
    <div class="main-menu-wrapper">
      <div class="menu-header">
        <a href="index.html" class="menu-logo">
          <img src=" {% static 'img/logo11.png' %}" class="img-fluid" alt="Logo" style="width:50px;height:50px">
        </a>
        <a id="menu_close" class="menu-close" href="javascript:void(0);">
          <i class="fas fa-times"></i>
        </a>
      </div>
      <ul class="main-nav">
        
        <li class="has-submenu active"> {% if user.is_authenticated %}
          <a href="#">Gestion PFE <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu"> 
            <li class="has-submenu">
              <a >demande de stage</a> 
              <ul class="submenu">
                <li><a href="{% url 'gestionpfe:binome' %}">Par binome</a></li>
                <li><a href="{% url 'gestionpfe:monome' %}">Monome</a></li>
              </ul>
            </li> 
            <li><a href="{% url 'gestionpfe:demandeC' %}">cahier de charge</a></li> 
            <li><a href="{% url 'gestionpfe:notifier' %}">notification</a></li>
            <li><a href="{% url 'gestionpfe:ficherecap' %}">Fiche Récap</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#"> Gestion CV <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
            <li><a href="doctor-dashboard.html"> Création CV</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#">Gestion .... <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
          </ul>
        </li>
        {% else %}
        

        <li class="login-link">
          <a href="{% url 'login' %}">Login / Signup</a>
        </li> {%endif%}
      </ul>
    </div>
    <ul class="nav header-navbar-rht">
      <li class="nav-item contact-item">
        <div class="header-contact-img">
          <i class="far fa-hospital"></i>
        </div>
        <div class="header-contact-detail">
          <p class="contact-header">Contact</p>
          <p class="contact-info-header"> +216 24 383 003 </p>
        </div>
      </li>
      {% if user.is_authenticated %}
      <!-- User Menu -->
      <li class="nav-item dropdown has-arrow logged-item">
        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
          <span class="user-img">
            <img class="rounded-circle" src="{% static 'img/userr.jpg' %}" width="31" alt="Darren Elder">
          </span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="user-header">
            <div class="avatar avatar-sm">
              <img src="{% static 'img/userr.jpg' %}" alt="User Image" class="avatar-img rounded-circle">
            </div>
            <div class="user-text">
              <h6>{{user}}</h6>
              <p class="text-muted mb-0">Etudiant(e)</p>
            </div>
          </div>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
         <!-- <a class="dropdown-item" href="{% url 'password_reset' %}">Logout</a> -->
        </div>
      </li>
      <!-- /User Menu -->
      {% else %}

      <li class="nav-item">
        <a class="nav-link header-login" href="{% url 'login' %}">login / Signup </a>
      </li>  {% endif %}
    </ul>
    
  </nav>
  
</header>


<!-- /Header -->

templates/includes/headeriden.html
{% load static %}
<header class="header">
  <nav class="navbar navbar-expand-lg header-nav">
    <div class="navbar-header">
      <a id="mobile_btn" href="javascript:void(0);">
        <span class="bar-icon">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </a>
      <a href="index.html" class="navbar-brand logo">
        <img src="{% static 'img/logo11.png' %}" class="img-fluid" alt="Logo" style="width:50px;height:50px">
      </a>
    </div>
    <div class="main-menu-wrapper">
      <div class="menu-header">
        <a href="index.html" class="menu-logo">
          <img src=" {% static 'img/logo11.png' %}" class="img-fluid" alt="Logo" style="width:50px;height:50px">
        </a>
        <a id="menu_close" class="menu-close" href="javascript:void(0);">
          <i class="fas fa-times"></i>
        </a>
      </div>
      <ul class="main-nav">
        
        <li class="has-submenu active">
          <a href="#">Gestion PFE <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
            <li class="has-submenu">
              <a >demande de stage</a>
              <ul class="submenu">
                <li><a href="{% url 'gestionpfe:binome' %}">Par binome</a></li>
                <li><a href="{% url 'gestionpfe:monome' %}">Monome</a></li>
              </ul>
            </li>
            <li><a href="{% url 'gestionpfe:demandeC' %}">cahier de charge</a></li>
            <li><a href="{% url 'gestionpfe:notifier' %}">notification</a></li>
            <li><a href="{% url 'gestionpfe:ficherecap' %}">Fiche récap</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#"> Gestion CV <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
            <li><a href="doctor-dashboard.html"> Création CV</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#">Gestion .... <i class="fas fa-chevron-down"></i></a>
          <ul class="submenu">
          </ul>
        </li>
        
        

        <li class="login-link">
          <a href="{% url 'login' %}">Login / Signup</a>
        </li>
      </ul>
    </div>
    <ul class="nav header-navbar-rht">
      <li class="nav-item contact-item">
        <div class="header-contact-img">
          <i class="far fa-hospital"></i>
        </div>
        <div class="header-contact-detail">
          <p class="contact-header">Contact</p>
          <p class="contact-info-header"> +216 24 383 003 </p>
        </div>
      </li>
     
      <!-- User Menu -->
      <li class="nav-item dropdown has-arrow logged-item">
        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
          <span class="user-img">
            <img class="rounded-circle" src="{% static 'img/userr.jpg' %}" width="31" alt="Darren Elder">
          </span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="user-header">
            <div class="avatar avatar-sm">
              <img src="{% static 'img/userr.jpg' %}" alt="User Image" class="avatar-img rounded-circle">
            </div>
            <div class="user-text">
              <h6>{{user}}</h6>
              <p class="text-muted mb-0">Etudiant(e)</p>
            </div>
          </div>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
      <!-- /User Menu -->
    </ul>
    
  </nav>
  
</header>


<!-- /Header -->