gestionp/urls.py
import statistics
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gestionpfe.urls',namespace='gestionpfe')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('social-auth/', include('social_django.urls', namespace="social")),
    
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionpfe/urls.py
from django.urls import path
from . import views
from django.views.static import serve 

app_name="gestionpfe"
urlpatterns = [
    path('',views.home,name='home'),
    path('signup/',views.register_request,name='signup'),
    path('monome/',views.monome,name='monome'),
    path('binome/',views.binome,name='binome'),
    path('updatebinome/',views.updateDatabinome,name="updatebinome"),
    path('updatemonome/',views.updateDatamonome,name="updatemonome"),
    path('CahierCharge/',views.cahierC,name='demandeC'),
    path('ficherecap/',views.ficherecap,name='ficherecap'),
    path('test/',views.subscribe,name='subscribe'),
    path("reponse/<int:pk>/<slug:userlogin>/",views.reponse,name='reponse'),
    path("notif/",views.notifier,name='notifier'),
    
    
    
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>PFE</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

		<!-- Favicons -->
		<link type="image/x-icon" href="{% static 'img/logo11.png' %}" rel="icon">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- Fontawesome CSS -->
		<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css' %}">
		
		<!-- Swiper CSS -->
		<link rel="stylesheet" href="{% static 'plugins/swiper/css/swiper.min.css' %}">

		<!-- Main CSS -->
		<link rel="stylesheet" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="{% static 'js/html5shiv.min.js"></script>
			<script src="{% static 'js/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>

		<!-- Main Wrapper -->
		<div class="main-wrapper">
      {% include 'includes/header.html' %}
      {%  block content %}
      {% endblock content %}
      {% include 'includes/footer.html' %}

    </div>
<!-- /Main Wrapper -->

<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!-- Bootstrap Core JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Swiper JS -->
<script src="{% static 'plugins/swiper/js/swiper.min.js' %}"></script>

<!-- Slick JS -->
<script src="{% static 'js/slick.js' %}"></script>

<!-- Custom JS -->
<script src="{% static 'js/script.js' %}"></script>

</body>

</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>PFE</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

		<meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>

		<!-- Favicons -->
		<link type="image/x-icon" href="{% static 'img/logo11.png' %}" rel="icon">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

		<!-- Fontawesome CSS -->
		<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css' %}">
		
		<!-- Swiper CSS -->
		<link rel="stylesheet" href="{% static 'plugins/swiper/css/swiper.min.css' %}">

		<!-- Main CSS -->
		<link rel="stylesheet" href="{% static 'css/style.css' %}">

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="{% static 'js/html5shiv.min.js"></script>
			<script src="{% static 'js/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>

		<!-- Main Wrapper -->
		<div class="main-wrapper">
      {% include 'includes/headeriden.html' %}

	  
      {%  block content %}
      {% endblock content %}
 

    </div>
<!-- /Main Wrapper -->

<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!-- Bootstrap Core JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Swiper JS -->
<script src="{% static 'plugins/swiper/js/swiper.min.js' %}"></script>

<!-- Slick JS -->
<script src="{% static 'js/slick.js' %}"></script>

<!-- Custom JS -->
<script src="{% static 'js/script.js' %}"></script>

</body>

</html>

templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Subscribe</title>
</head>
<body>
<main>
    <h1>Subscribe</h1>
    {% if messages %}
        {% for message in messages %}
            <p style="color: red">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form action="{% url 'gestionpfe:subscribe' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        
        <input type="submit" value="Submit">
    </form>
</main>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

<div class="pharmacy-home-slider">
  <div class="swiper-container">
      <div class="swiper-wrapper">
          <div class="swiper-slide">
          </div>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
      <div class="banner-wrapper">
      <div class="banner-header text-center">
        <h1>Institut Supérieur des Etudes Technologiques de Nabeul</h1>
      </div>
    </div>
  </div>
  <!-- Add Pagination -->
  <div class="swiper-pagination"></div>
</div>
<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <h5 class="card-title">Institut Supérieur des Etudes Technologiques de Nabeul</h5>
    <p class="card-text">Envie d'améliorer votre candidature ! Bienvenue sur la plateforme professionnelle de gestion des PFE de l'ISET</p>
    <p class="card-text"> Ce Site vous permet de faire une demande de Stage et Cahier de charge </p>
    <p class="card-text"> Le contact avec votre encadrant</p>
    <p class="card-text"> Tout Ce que vous avez besoins , vous le trouvez ici </p>
    <p class="card-text"> Bon courage </p>
  </div>
</div>

{% endblock content %}

templates/notif.html
{% extends 'base.html' %}
{% load static %}
{%load crispy_forms_tags %}
{% block content %}


  {% for key in noti %}
  {% if key.content == "1" %} 
  <div class="alert alert-success" role="alert">
    success welcome
  </div>
  {% else %} 
  <div class="alert alert-danger" role="alert">
    refus malheureusement
  </div>
  {% endif %}
  {% endfor %}

{% endblock content %}

templates/welcome.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Simple Transactional Email</title>
    <style>
      /* -------------------------------------
          GLOBAL RESETS
      ------------------------------------- */
      img {
        border: none;
        -ms-interpolation-mode: bicubic;
        max-width: 100%; }
      body {
        background-color: #f6f6f6;
        font-family: sans-serif;
        -webkit-font-smoothing: antialiased;
        font-size: 14px;
        line-height: 1.4;
        margin: 0;
        padding: 0; 
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%; }
      table {
        border-collapse: separate;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
        width: 100%; }
        table td {
          font-family: sans-serif;
          font-size: 14px;
          vertical-align: top; }
      /* -------------------------------------
          BODY & CONTAINER
      ------------------------------------- */
      .body {
        background-color: #f6f6f6;
        width: 100%; }
      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
        display: block;
        Margin: 0 auto !important;
        /* makes it centered */
        max-width: 580px;
        padding: 10px;
        width: 580px; }
      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
        box-sizing: border-box;
        display: block;
        Margin: 0 auto;
        max-width: 580px;
        padding: 10px; }
      /* -------------------------------------
          HEADER, FOOTER, MAIN
      ------------------------------------- */
      .main {
        background: #fff;
        border-radius: 3px;
        width: 100%; }
      .wrapper {
        box-sizing: border-box;
        padding: 20px; }
      .footer {
        clear: both;
        padding-top: 10px;
        text-align: center;
        width: 100%; }
        .footer td,
        .footer p,
        .footer span,
        .footer a {
          color: #999999;
          font-size: 12px;
          text-align: center; }
      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1,
      h2,
      h3,
      h4 {
        color: #000000;
        font-family: sans-serif;
        font-weight: 400;
        line-height: 1.4;
        margin: 0;
        Margin-bottom: 30px; }
      h1 {
        font-size: 35px;
        font-weight: 300;
        text-align: center;
        text-transform: capitalize; }
      p,
      ul,
      ol {
        font-family: sans-serif;
        font-size: 14px;
        font-weight: normal;
        margin: 0;
        Margin-bottom: 15px; }
        p li,
        ul li,
        ol li {
          list-style-position: inside;
          margin-left: 5px; }
      a {
        color: #3498db;
        text-decoration: underline; }
      /* -------------------------------------
          BUTTONS
      ------------------------------------- */
      .btn {
        box-sizing: border-box;
        width: 100%; }
        .btn > tbody > tr > td {
          padding-bottom: 15px; }
        .btn table {
          width: auto; }
        .btn table td {
          background-color: #ffffff;
          border-radius: 5px;
          text-align: center; }
        .btn a {
          background-color: #ffffff;
          border: solid 1px #3498db;
          border-radius: 5px;
          box-sizing: border-box;
          color: #3498db;
          cursor: pointer;
          display: inline-block;
          font-size: 14px;
          font-weight: bold;
          margin: 0;
          padding: 12px 25px;
          text-decoration: none;
          text-transform: capitalize; }
      .btn-primary table td {
        background-color: #3498db; }
      .btn-primary a {
        background-color: #3498db;
        border-color: #3498db;
        color: #ffffff; }
      /* -------------------------------------
          OTHER STYLES THAT MIGHT BE USEFUL
      ------------------------------------- */
      .last {
        margin-bottom: 0; }
      .first {
        margin-top: 0; }
      .align-center {
        text-align: center; }
      .align-right {
        text-align: right; }
      .align-left {
        text-align: left; }
      .clear {
        clear: both; }
      .mt0 {
        margin-top: 0; }
      .mb0 {
        margin-bottom: 0; }
      .preheader {
        color: transparent;
        display: none;
        height: 0;
        max-height: 0;
        max-width: 0;
        opacity: 0;
        overflow: hidden;
        mso-hide: all;
        visibility: hidden;
        width: 0; }
      .powered-by a {
        text-decoration: none; }
      hr {
        border: 0;
        border-bottom: 1px solid #f6f6f6;
        Margin: 20px 0; }
      /* -------------------------------------
          RESPONSIVE AND MOBILE FRIENDLY STYLES
      ------------------------------------- */
      @media only screen and (max-width: 620px) {
        table[class=body] h1 {
          font-size: 28px !important;
          margin-bottom: 10px !important; }
        table[class=body] p,
        table[class=body] ul,
        table[class=body] ol,
        table[class=body] td,
        table[class=body] span,
        table[class=body] a {
          font-size: 16px !important; }
        table[class=body] .wrapper,
        table[class=body] .article {
          padding: 10px !important; }
        table[class=body] .content {
          padding: 0 !important; }
        table[class=body] .container {
          padding: 0 !important;
          width: 100% !important; }
        table[class=body] .main {
          border-left-width: 0 !important;
          border-radius: 0 !important;
          border-right-width: 0 !important; }
        table[class=body] .btn table {
          width: 100% !important; }
        table[class=body] .btn a {
          width: 100% !important; }
        table[class=body] .img-responsive {
          height: auto !important;
          max-width: 100% !important;
          width: auto !important; }}
      @media all {
        .ExternalClass {
          width: 100%; }
        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
          line-height: 100%; }
        .apple-link a {
          color: inherit !important;
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          text-decoration: none !important; } 
        .btn-primary table td:hover {
          background-color: #34495e !important; }
        .btn-primary a:hover {
          background-color: #34495e !important;
          border-color: #34495e !important; } }
    </style>
  </head>
  <body class="">
    <table border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <td>&nbsp;</td>
        <td class="container">
          <div class="content">
            <span class="preheader">Subscribe to Coloured.com.ng mailing list</span>
            <form action="" method="POST">
                               
                               
            <table class="main">
           

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper">
                  <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td>
                        <h1>Confirm Cahier Charge - {{name}}</h1>
                        <h2>Bonjour M.</h2>
                        <h3>Je vous sollicite, afin de vous demander si vous accepteriez de devenir mon Encadreur(ante) du projet de fin d'études</h3>
                        <h3> Voici Mon Cahier de Charge de Mon Projet </h3>
                        <h2 style="color:blue;"> Nom de Projet : {{nomprojet}}</h2>
                        <h2 style="color:blue;"> Description de Project  : {{description}}</h2>
                        <h2 style="color:blue;"> Besoins Fonctionelle : {{besoin}}</h2>
                        <h2 style="color:blue;"> Delais : {{delais}} </h2>
                         <h3>N’hésitez pas à me contacter si vous désirez plus de précisions sur mon sujet.</h3>
                        <h3>Dans l’attente de votre réponse de votre part.</h3>
                        <h3>Bien à vous. </h3>  
                        <table border="0" cellpadding="0" cellspacing="0" class="btn btn-primary">
                          <tbody>
                            <tr>
                              <td align="left">
                                <table border="0" cellpadding="0" cellspacing="0">
                                  <tbody>
                                    <tr>
                                      <td> <a href="http://localhost:8000/reponse/1/{{name}}" target="_blank">Accept</a> </td> 
                                      <td> <a href="http://localhost:8000/reponse/0/{{name}}" target="_blank">Refus</a> </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>
        </form> 
            <!-- START FOOTER -->
            <div class="footer">
              <table border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <span class="apple-link">Coloured.com.ng | Feminism | Culture | Law | Feminists Rising</span>
                    <br> Don't like these emails? <a href="#">Unsubscribe</a>.
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->
            
          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td>&nbsp;</td>
      </tr>
    </table>
    
  </body>
</html>