gestionp/urls.py
import statistics
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gestionpfe.urls',namespace='gestionpfe')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('social-auth/', include('social_django.urls', namespace="social")),
    
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionpfe/urls.py
from django.urls import path
from . import views
from django.views.static import serve 

app_name="gestionpfe"
urlpatterns = [
    path('',views.home,name='home'),
    path('signup/',views.register_request,name='signup'),
    path('monome/',views.monome,name='monome'),
    path('binome/',views.binome,name='binome'),
    path('updatebinome/',views.updateDatabinome,name="updatebinome"),
    path('updatemonome/',views.updateDatamonome,name="updatemonome"),
    path('CahierCharge/',views.cahierC,name='demandeC'),
    path('ficherecap/',views.ficherecap,name='ficherecap'),
    path('test/',views.subscribe,name='subscribe'),
    path("reponse/<int:pk>/<slug:userlogin>/",views.reponse,name='reponse'),
    path("notif/",views.notifier,name='notifier'),
    
    
    
    
]

templates/parts/CahierCharge.html
{% extends 'base.html' %}
{% load static %}
{%load crispy_forms_tags %}
{% block content %}


<!-- Basic Information -->
<div class="card">
    <div class="card-body">
        <h2 class="card-title" style="text-align:center;">Cahier de Charge</h2>
        {% if messages %}
        {% for message in messages %}
           <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
           <script>  
                var m= '{{message}}';
                swal("Perfect !", m , "success");
            </script>

        {% endfor %}
    {% endif %}
        <form enctype='multipart/form-data' method="post">
            {% csrf_token %}
        <div class="row form-row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="change-avatar">
                        <div class="upload-img">
                            <div class="change-photo-btn">
                                <span><i class="fa fa-upload"></i> Upload Fichier scannee</span>
                                <input type="file" class="upload" name="document" id="document"> 
                            </div> 
                        </div>  
                        <div class="upload-img"> 
                            <div class="change-photo-btn">
                                <span><i class="fa fa-upload"></i> Upload Autre Fichier</span>
                                <input type="file" class="upload" name="document2" id="document2" >
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="form-group">
                    <label>Nom de projet <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="projet">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Description <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="descrip">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Besoins fonctionnels <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="besoin">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Delais <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="delai">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Emails des Encadrants <span class="text-danger">*</span></label> <br> <br>
                    <select name="email"> 
                        {% for n in notes %} 
                        <option name="email" value="{{n.id}}"> {{ n.mail }}</option> 
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="submit-section submit-btn-bottom">
    <button type="submit" class="btn btn-primary submit-btn">Save</button>
</div>
  </form>
<!-- /Basic Information -->



{% endblock content %}

templates/parts/binome.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="row">
          <div class="col-md-12 offset-md-2">
           
            <div class="account-content ">

              <div class="row" >


                <div class="col-md-10 login-right ">
                  
                        <div class="login-header">
                          <h3 style="text-align:center;">Demande de Stage</h3> <br/>
                          <h6>Les coordonnées de l'étudiant:</h6> 
                          <h3 style="text-align:right;">Stage:Binome</h3>
                        </div>
                    <form method="post">
                      {% csrf_token %} 
                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">Nom &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="nom1">
                              </div>
                              <label class="label" style="text-align:center;">Nom2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="text" name="nom2">
                              </div>
                            </div>
                          </div>

                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">Prénom &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="prenom1">
                              </div>
                              <label class="label" style="text-align:center;">Prénom2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="text" name="prenom2">
                              </div>
                            </div>
                          </div>

                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">NCin &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="cin1">
                              </div>
                              <label class="label" style="text-align:center;">Ncin2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="text" name="cin2">
                              </div>
                            </div>
                          </div>

                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">E-mail &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="mail1">
                              </div>
                              <label class="label" style="text-align:center;">E-mail2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="Email" name="mail2">
                              </div>
                            </div>
                          </div>

                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">Parcours1 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <div class="select is-normal">
                                  <select name="parcours1" value='{{user.parcours1}}'>
                                    <option value="DSI" name="parcours1">DSI</option>
                                    <option value="SEM" name="parcours1">SEM</option>
                                    <option value="RSI" name="parcours1">RSI</option>
                                    <option value="MDW" name="parcours1">MDW</option>
                                  </select>
                                </div>
                              </div> &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                              <label class="label" style="text-align:center;">Parcours2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <div class="select is-normal">
                                  <select name="parcours2" value='{{user.parcours2}}'>
                                    <option value="DSI" name="parcours2"> DSI</option>
                                    <option value="SEM"name="parcours2"> SEM</option>
                                    <option value="RSI"name="parcours2"> RSI</option>
                                    <option value="MDW" name="parcours2"> MDW</option>
                                  </select>
                                </div> 
                              </div>
                            </div>
                          </div> 
                          <button class="button is-primary">
                            valider
                          </button>
                    </form> 
                    
                  
<hr> 
<label class="label" style="text-align:left;">Concerne la Société:</label>
<br>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">Nom du Société : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ......................... </i> </label>
  </div>
</div>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">adresse du société: &nbsp;&nbsp;<i style="color:grey">  ....................... </i> </label>
  </div>

</div>


<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">Domaine du Société: &nbsp;&nbsp;<i style="color:grey">  ....................... </i> </label>
  </div>
</div>


<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">Signature</label>
    <label class="label"><i style="color:grey">  ....................... </i> </label>
  </div>
</div>


</div>

  </div>
    </div> 
      </div>
        </div>
          </div> 
            </div> 
              </div> 
                </div>   
              
             
                <br/>
                

{% endblock content %}

templates/parts/document.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}


<div class="card" id="printBox" >
    <div class="row">
        <div class="col" style="text-align:left;"><h5  style="text-align:center;"> Institut superieur des Etudes Technologique de Nabeul</h5></div>
        <div class="col">  <center> <img src="{% static 'img/logoiset.png' %}" alt="logo" style="width:60px;height:60px;"> </img> </center>  </div> 
        <div class="col" style="text-align:right"> <h5 style="text-align:center;"> <b> المعهد العالي للدراسات التكنولوجية بنابل </b></h5> </div>
    </div>

  <hr> 

<h2 style="text-align:center;color:grey;">  Demande De Stage </h2>
<hr>
<div>
    <h3 >Les Coordonnées de L'étudiant:</h3>
    <h3 style="text-align:right;">Stage: Monome</h3>
</div>                  
<div> 
   <h4> Nom :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ nom }}</h4> 
</div> <br>
<div> 
    <h4> Prénom :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ prenom1 }} </h4> 
</div> <br>
<div> 
    <h4> Ncin :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ cin }}</h4> 
</div>  <br>
<div> 
    <h4> Parcours :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ parcour }} </h4> 
</div> <br>
 <div> 
    <h4> E-mail :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ email }} </h4> 
 </div> 

 <hr> 

 <label class="label" style="text-align:left;"> <h3> Concerne la Société: </h3> </label>

   <br> 

   <div>
     <h4 style="text-align:left;"> Nom du Société : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ....................... </i></h4>
 </div> <br>

   <div >
     <h4 style="text-align:left;">Adresse du Société: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ....................... </i> </h4>
 </div> <br>  
 
 

<div >
     <h4 style="text-align:left;">Domaine du Société: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ....................... </i></h4>
 </div>

 
<div style="text-align:right;">
       <h4 style="text-align:right;">Signature <br> <i style="color:grey">  ....................... </i> </h4>
</div>


</div>


   

  <button class="button is-primary"  onclick="myFunction()">
    imprimer
  </button>

  <script>
    function myFunction()
{
    var mywindow = window.open('', 'PRINT', 'height=400,width=600');
    mywindow.document.write(document.getElementById("printBox").innerHTML);
    mywindow.document.close();
    mywindow.focus(); 
    mywindow.print();
    mywindow.close();
    return true;
}
       
    </script>
    {% endblock content %}

templates/parts/document4.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}


<div class="card" id="printBox" >
    <div class="row">
        <div class="col" style="text-align:left;"><h5  style="text-align:center;"> Institut superieur des Etudes Technologique de Nabeul</h5></div>
        <div class="col">  <center> <img src="{% static 'img/logoiset.png' %}" alt="logo" style="width:60px;height:60px;"> </img> </center>  </div> 
        <div class="col" style="text-align:right"> <h5 style="text-align:center;"> <b> المعهد العالي للدراسات التكنولوجية بنابل </b></h5> </div>
    </div>

  <hr> 

<h2 style="text-align:center;color:grey;">  Demande De Stage </h2>
<hr>
<div>
    <h3 >Les Coordonnées de L'étudiant:</h3>
    <h3 style="text-align:right;">Stage: Monome</h3>
</div>                  
<div> 
   <h4> Nom :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ user.nom }}</h4> 
</div> <br>
<div> 
    <h4> Prénom :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ user.prenom }} </h4> 
</div> <br>
<div> 
    <h4> Ncin :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ user.ncin }}</h4> 
</div>  <br>
<div> 
    <h4> Parcours :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ user.parcours }} </h4> 
</div> <br>
 <div> 
    <h4> E-mail :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ user.email }} </h4> 
 </div> 

 <hr> 

 <label class="label" style="text-align:left;"> <h3> Concerne la Société: </h3> </label>

   <br> 

   <div>
     <h4 style="text-align:left;"> Nom du Société : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ....................... </i></h4>
 </div> <br>

   <div >
     <h4 style="text-align:left;">Adresse du Société: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ....................... </i> </h4>
 </div> <br>  
 
 

<div >
     <h4 style="text-align:left;">Domaine du Société: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ....................... </i></h4>
 </div>

 
<div style="text-align:right;">
       <h4 style="text-align:right;">Signature <br> <i style="color:grey">  ....................... </i> </h4>
</div>


</div>


   

  <button class="button is-primary"  onclick="myFunction()">
    imprimer
  </button>

  <script>
    function myFunction()
{
    var mywindow = window.open('', 'PRINT', 'height=400,width=600');
    mywindow.document.write(document.getElementById("printBox").innerHTML);
    mywindow.document.close();
    mywindow.focus(); 
    mywindow.print();
    mywindow.close();
    return true;
}
       
    </script>
    {% endblock content %}

templates/parts/response.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Subscribe</title>
</head>
<body>
<main>
    <h1>  votre msg est envoye </h1>
    
    </form>
</main>
</body>
</html>

templates/parts/update.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="row">
          <div class="col-md-12 offset-md-2">

            <div class="account-content ">

              <div class="row" >


                <div class="col-md-10 login-right ">

                        <div class="login-header">
                          <h3 style="text-align:center;">Demande de Stage</h3> <br/>
                          <h6>Les coordonnées de l'étudiant:</h6>
                          <h3 style="text-align:right;">Stage:Binome</h3>
                        </div>
                    <form method="post" action="{% url 'gestionpfe:updatebinome' %}">
                      {% csrf_token %}
                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">Nom &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="nom1" value='{{user.nom}}'>
                              </div>
                              <label class="label" style="text-align:center;">Nom2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="text" name="nom2" value='{{user.nom2}}'>
                              </div>
                            </div>
                          </div>

                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">Prénom &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="prenom1" value='{{user.prenom}}'>
                              </div>
                              <label class="label" style="text-align:center;">Prénom2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="text" name="prenom2" value='{{user.prenom2}}'>
                              </div>
                            </div>
                          </div>
                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">NCin &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="cin1" value='{{user.ncin}}'>
                              </div>
                              <label class="label" style="text-align:center;">Ncin2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="text" name="cin2" value='{{user.ncin2}}'>
                              </div>
                            </div>
                          </div>

                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">E-mail &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <input class="input" type="text" name="mail1" value='{{user.email}}'>
                              </div>
                              <label class="label" style="text-align:center;">E-mail2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <input class="input" type="Email" name="mail2" value='{{user.email2}}'>
                              </div>
                            </div>
                          </div>

                          <div class="field is-horizontal">
                            <div class="field-body">
                              <label class="label" style="text-align:center;">Parcours &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left">
                                <div class="select is-normal">
                                  <select name="parcours1">
                                    <option value="DSI" {% if user.parcours == 'DSI' %}selected{% endif %}> DSI</option>
                                    <option value="SEM" {% if user.parcours == 'SEM' %}selected{% endif %}> SEM</option>
                                    <option value="RSI" {% if user.parcours  == 'RSI' %}selected{% endif %}> RSI</option>
                                    <option value="MDW" {% if user.parcours == 'MDW' %}selected{% endif %}> MDW</option>
                                  </select>
                                </div>
                              </div> &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                              <label class="label" style="text-align:center;">Parcours2 &nbsp;&nbsp;</label>
                              <div class="control is-expanded has-icons-left has-icons-right">
                                <div class="select is-normal">
                                  <select name="parcours2">
                                    <option value="DSI" {% if user.parcours2 == 'DSI' %}selected{% endif %}> DSI</option>
                                    <option value="SEM" {% if user.parcours2 == 'SEM' %}selected{% endif %}> SEM</option>
                                    <option value="RSI" {% if user.parcours2 == 'RSI' %}selected{% endif %}> RSI</option>
                                    <option value="MDW" {% if user.parcours2 == 'MDW' %}selected{% endif %}> MDW</option>
                                  </select>
                                </div>
                              </div>
                            </div>
                          </div>
                          <button class="button is-primary" type="submit">
                            update
                          </button> 
                    </form>


<hr>
<label class="label" style="text-align:left;">Concerne la Société:</label>
<br>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">Nom du Société : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ......................... </i> </label>
  </div>
</div>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">adresse du société: &nbsp;&nbsp;<i style="color:grey">  ....................... </i> </label>
  </div>

</div>


<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">Domaine du Société: &nbsp;&nbsp;<i style="color:grey">  ....................... </i> </label>
  </div>
</div>


<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">Signature</label>
    <label class="label"><i style="color:grey">  ....................... </i> </label>
  </div>
</div>


</div>

  </div>
    </div>
      </div>
        </div>
          </div>
            </div>
              </div>
                </div>


                <br/>


{% endblock content %}

templates/parts/updatemonome.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="row">
          <div class="col-md-12 offset-md-2">
           
            <div class="account-content ">

              <div class="row" >


                <div class="col-md-10 login-right ">
                  
                        <div class="login-header" >
                          <h3 style="text-align:center;">Demande de Stage</h3> <br/>
                          <h6>Les coordonnées de l'étudiant:</h6>
                          <h3 style="text-align:right;">Stage: Monome</h3>
                        </div> 
                          <form method="post" action={%  url 'gestionpfe:updatemonome'  %}>
                            {% csrf_token %} 
                            <div class="field">
                              <label class="label">Nom</label>
                              <div class="control">
                                <input class="input" type="text" name="nom" value='{{user.nom}}'>
                              </div>
                            </div>

                            <div class="field">
                              <label class="label">Prénom</label>
                              <div class="control">
                                <input class="input" type="text" name="prenom" value='{{user.prenom}}'>
                              </div>
                            </div>

                            <div class="field">
                              <label class="label">NumCin</label>
                              <div class="control">
                                <input class="input" type="text" name="cin" value='{{user.ncin}}'>
                              </div>
                            </div>

                            
                            <div class="field is-horizontal">
                              <div class="field-body">
                                <div class="field">
                                  <label class="label" >Parcours:</label> 
                            <div class="control">
                              <div class="select is-normal">
                                <select name="parcours" value='{{user.parcour}}'>
                                  <option value="dsi" name="parcours" {% if user.parcours == 'dsi' %}selected{% endif %}>DSI</option>
                                  <option value="sem" name="parcours" {% if user.parcours == 'sem' %}selected{% endif %}>SEM</option>
                                  <option value="rsi" name="parcours" {% if user.parcours == 'rsi' %}selected{% endif %}>RSI</option>
                                  <option value="mdw" name="parcours" {% if user.parcours == 'mdw' %}selected{% endif %}>MDW</option>
                                </select>
                              </div>
                            </div>

                            <div class="field is-horizontal">
                              <div class="field-body">
                            <div class="field">
                              <label class="label">Email</label>
                              <div class="control">
                                <input class="input" type="email" placeholder="e.g. alexsmith@gmail.com" name="email" value='{{user.email}}'>
                              </div>
                            </div>
                            </div>
                          </div>
                          
                    </form>
                

<hr> 
<label class="label" style="text-align:left;">concerne la société:</label>
<br>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">Nom du Société : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i style="color:grey">  ......................... </i> </label>
  </div>
</div>

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">adresse du société: &nbsp;&nbsp;<i style="color:grey">  ....................... </i> </label>
  </div>

</div>


<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label" style="text-align:left;">Domaine du Société: &nbsp;&nbsp;<i style="color:grey">  ....................... </i> </label>
  </div>
</div>


<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">Signature</label>
    <label class="label"><i style="color:grey">  ....................... </i> </label>
  </div>
</div>


<div class="field is-horizontal">
  <div class="field-label">
    <!-- Left empty for spacing -->
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <button class="button is-primary" type="submit">
          Update
        </button>
      </div>
    </div>
  </div>
</div>
</div>

  </div>
    </div> 
      </div>
        </div>
          </div> 
            </div> 
              </div> 
                </div>   
      
             
                <br/>
                
<br>

{% endblock content %}